version: '3'

services:
###> doctrine/doctrine-bundle ##

  php:
    build:
      context: .docker/php
      dockerfile: dockerfile-php
    volumes:
      - ./symfony:/var/www/symfony/
    networks:
      - symfony

  nginx:
    build:
      context: .docker/nginx
      dockerfile: dockerfile-nginx
    volumes:
      - ./symfony:/var/www/symfony/
    ports:
      - 80:80
    networks:
      - symfony

  mysql57:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '%env(MYSQL_ROOT_PASSWORD)%'
      MYSQL_DATABASE: '%env(MYSQL_DATABASE)%'
      MYSQL_USER: '%env(MYSQL_USER)%'
      MYSQL_PASSWORD: '%env(MYSQL_PASSWORD)%'

    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - symfony
    volumes:
      - ./symfony:/var/lib/mysql


volumes:
  db-data:

networks:
  symfony:
